<option value="Abkhazian">Abkhazian</option>
<option value="Afar">Afar</option>
<option value="Akan">Akan</option>
<option value="Albanian">Albanian</option>
<option value="Amharic">Amharic</option>
<option value="Arabic">Arabic</option>
<option value="Aragonese">Aragonese</option>
<option value="Armenian">Armenian</option>
<option value="Assamese">Assamese</option>
<option value="Avaric">Avaric</option>
<option value="Avestan">Avestan</option>
<option value="Aymara">Aymara</option>
<option value="Azerbaijani">Azerbaijani</option>
<option value="Bambara">Bambara</option>
<option value="Bashkir">Bashkir</option>
<option value="Basque">Basque</option>
<option value="Belarusian">Belarusian</option>
<option value="Bengali">Bengali</option>
<option value="Bihari">Bihari</option>
<option value="Bislama">Bislama</option>
<option value="Bosnian">Bosnian</option>
<option value="Breton">Breton</option>
<option value="Bulgarian">Bulgarian</option>
<option value="Burmese">Burmese</option>
<option value="Catalan, Valencian">Catalan, Valencian</option>
<option value="Chamorro">Chamorro</option>
<option value="Chechen">Chechen</option>
<option value="Chichewa, Chewa, Nyanja">Chichewa, Chewa, Nyanja</option>
<option value="Chinese">Chinese</option>
<option value="Chuvash">Chuvash</option>
<option value="Cornish">Cornish</option>
<option value="Corsican">Corsican</option>
<option value="Cree">Cree</option>
<option value="Croatian">Croatian</option>
<option value="Czech">Czech</option>
<option value="Danish">Danish</option>
<option value="Divehi, Dhivehi, Maldivian">Divehi, Dhivehi, Maldivian</option>
<option value="Dutch">Dutch</option>
<option value="English" selected>English</option>
<option value="Esperanto">Esperanto</option>
<option value="Estonian">Estonian</option>
<option value="Ewe">Ewe</option>
<option value="Faroese">Faroese</option>
<option value="Fijian">Fijian</option>
<option value="Finnish">Finnish</option>
<option value="French">French</option>
<option value="Fula, Fulah, Pulaar, Pular">Fula, Fulah, Pulaar, Pular</option>
<option value="Galician">Galician</option>
<option value="Georgian">Georgian</option>
<option value="German">German</option>
<option value="Greek, Modern">Greek, Modern</option>
<option value="Guaraní">Guaraní</option>
<option value="Gujarati">Gujarati</option>
<option value="Haitian; Haitian Creole">Haitian; Haitian Creole</option>
<option value="Hausa">Hausa</option>
<option value="Hebrew (modern)">Hebrew (modern)</option>
<option value="Herero">Herero</option>
<option value="Hindi">Hindi</option>
<option value="Hiri Motu">Hiri Motu</option>
<option value="Hungarian">Hungarian</option>
<option value="Interlingua">Interlingua</option>
<option value="Indonesian">Indonesian</option>
<option value="Interlingue">Interlingue</option>
<option value="Irish">Irish</option>
<option value="Igbo">Igbo</option>
<option value="Inupiaq">Inupiaq</option>
<option value="Ido">Ido</option>
<option value="Icelandic">Icelandic</option>
<option value="Italian">Italian</option>
<option value="Inuktitut">Inuktitut</option>
<option value="Japanese">Japanese</option>
<option value="Javanese">Javanese</option>
<option value="Kalaallisut, Greenlandic">Kalaallisut, Greenlandic</option>
<option value="Kannada">Kannada</option>
<option value="Kanuri">Kanuri</option>
<option value="Kashmiri">Kashmiri</option>
<option value="Kazakh">Kazakh</option>
<option value="Khmer">Khmer</option>
<option value="Kikuyu, Gikuyu">Kikuyu, Gikuyu</option>
<option value="Kinyarwanda">Kinyarwanda</option>
<option value="Kirghiz, Kyrgyz">Kirghiz, Kyrgyz</option>
<option value="Komi">Komi</option>
<option value="Kongo">Kongo</option>
<option value="Korean">Korean</option>
<option value="Kurdish">Kurdish</option>
<option value="Kwanyama, Kuanyama">Kwanyama, Kuanyama</option>
<option value="Latin">Latin</option>
<option value="Luxembourgish, Letzeburgesch">Luxembourgish, Letzeburgesch</option>
<option value="Luganda">Luganda</option>
<option value="Limburgish, Limburgan, Limburger">Limburgish, Limburgan, Limburger</option>
<option value="Lingala">Lingala</option>
<option value="Lao">Lao</option>
<option value="Lithuanian">Lithuanian</option>
<option value="Luba-Katanga">Luba-Katanga</option>
<option value="Latvian">Latvian</option>
<option value="Manx">Manx</option>
<option value="Macedonian">Macedonian</option>
<option value="Malagasy">Malagasy</option>
<option value="Malay">Malay</option>
<option value="Malayalam">Malayalam</option>
<option value="Maltese">Maltese</option>
<option value="Māori">Māori</option>
<option value="Marathi (Marāṭhī)">Marathi (Marāṭhī)</option>
<option value="Marshallese">Marshallese</option>
<option value="Mongolian">Mongolian</option>
<option value="Nauru">Nauru</option>
<option value="Navajo, Navaho">Navajo, Navaho</option>
<option value="Norwegian Bokmål">Norwegian Bokmål</option>
<option value="North Ndebele">North Ndebele</option>
<option value="Nepali">Nepali</option>
<option value="Ndonga">Ndonga</option>
<option value="Norwegian Nynorsk">Norwegian Nynorsk</option>
<option value="Norwegian">Norwegian</option>
<option value="Nuosu">Nuosu</option>
<option value="South Ndebele">South Ndebele</option>
<option value="Occitan">Occitan</option>
<option value="Ojibwe, Ojibwa">Ojibwe, Ojibwa</option>
<option value="Old Church Slavonic, Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic">Old Church Slavonic,
    Church Slavic, Church Slavonic, Old Bulgarian, Old Slavonic</option>
<option value="Oromo">Oromo</option>
<option value="Oriya">Oriya</option>
<option value="Ossetian, Ossetic">Ossetian, Ossetic</option>
<option value="Panjabi, Punjabi">Panjabi, Punjabi</option>
<option value="Pāli">Pāli</option>
<option value="Persian">Persian</option>
<option value="Polish">Polish</option>
<option value="Pashto, Pushto">Pashto, Pushto</option>
<option value="Portuguese">Portuguese</option>
<option value="Quechua">Quechua</option>
<option value="Romansh">Romansh</option>
<option value="Kirundi">Kirundi</option>
<option value="Romanian, Moldavian, Moldovan">Romanian, Moldavian, Moldovan</option>
<option value="Russian">Russian</option>
<option value="Sanskrit (Saṁskṛta)">Sanskrit (Saṁskṛta)</option>
<option value="Sardinian">Sardinian</option>
<option value="Sindhi">Sindhi</option>
<option value="Northern Sami">Northern Sami</option>
<option value="Samoan">Samoan</option>
<option value="Sango">Sango</option>
<option value="Serbian">Serbian</option>
<option value="Scottish Gaelic; Gaelic">Scottish Gaelic; Gaelic</option>
<option value="Shona">Shona</option>
<option value="Sinhala, Sinhalese">Sinhala, Sinhalese</option>
<option value="Slovak">Slovak</option>
<option value="Slovene">Slovene</option>
<option value="Somali">Somali</option>
<option value="Southern Sotho">Southern Sotho</option>
<option value="Spanish; Castilian">Spanish; Castilian</option>
<option value="Sundanese">Sundanese</option>
<option value="Swahili">Swahili</option>
<option value="Swati">Swati</option>
<option value="Swedish">Swedish</option>
<option value="Tamil">Tamil</option>
<option value="Telugu">Telugu</option>
<option value="Tajik">Tajik</option>
<option value="Thai">Thai</option>
<option value="Tigrinya">Tigrinya</option>
<option value="Tibetan Standard, Tibetan, Central">Tibetan Standard, Tibetan, Central</option>
<option value="Turkmen">Turkmen</option>
<option value="Tagalog">Tagalog</option>
<option value="Tswana">Tswana</option>
<option value="Tonga (Tonga Islands)">Tonga (Tonga Islands)</option>
<option value="Turkish">Turkish</option>
<option value="Tsonga">Tsonga</option>
<option value="Tatar">Tatar</option>
<option value="Twi">Twi</option>
<option value="Tahitian">Tahitian</option>
<option value="Uighur, Uyghur">Uighur, Uyghur</option>
<option value="Ukrainian">Ukrainian</option>
<option value="Urdu">Urdu</option>
<option value="Uzbek">Uzbek</option>
<option value="Venda">Venda</option>
<option value="Vietnamese">Vietnamese</option>
<option value="Volapük">Volapük</option>
<option value="Walloon">Walloon</option>
<option value="Welsh">Welsh</option>
<option value="Wolof">Wolof</option>
<option value="Western Frisian">Western Frisian</option>
<option value="Xhosa">Xhosa</option>
<option value="Yiddish">Yiddish</option>
<option value="Yoruba">Yoruba</option>
<option value="Zhuang, Chuang">Zhuang, Chuang</option>